eureka:
  client:
    service-url:
      #defaultZone: http://47.107.99.108:9001/eureka
      defaultZone: http://127.0.0.1:9001/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 15
    prefer-ip-address: true
server:
  port: 8081
